config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :tweets do 
    #post :follower #es el metodo creado en tweet controller para poder crear el seguir friend
    resources :likes 
    member do
      post :retweet #es el metodo creado en tweet controller para dar la acción 
    end
  end

  namespace :api do
    resources :tweets
  end

  # resources :users do 
  #   resources :friends
  # end

  get '/:hashtag', to: 'tweets#hashtag_search', as: 'hashtag'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
    } 

    devise_scope :user do
      post 'follow/:id', to: 'friends#follow', as: 'follow_user'
    delete 'follow/:id', to: 'friends#unfollow', as: 'unfollow_user'
    end
    
    get '/api/news', to: 'api/apis#index'
    get "/api/:date1/:date2", to: 'api/apis#date'
    post '/api/create', to: 'api/apis#create'
    get 'mytweets/index'

  root "tweets#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    belongs_to :user
    has_many :likes, dependent: :destroy
    validates :content, presence: true
    paginates_per 50
    #se define un metodo que guarda el campo del rt_ref encontrado del tweet
    
    scope :tweets_for_me, -> (user) { Tweet.where(user_id: user.friends.pluck(:friend_id).uniq) }


    
    #scope :tweets_for_me, -> (following_friends) { where user_id: following_friends }

    def retweet_ref
        Tweet.find(self.rt_ref)
    end

    def self.search_my_tweets(x)
        @my_tweets = Tweet.all
        my_tweet_id_array = []
        @my_tweets.each do |my_tweet|
            if my_tweet.content.include? "#{x}"
                my_tweet_id_array << my_tweet.id
            end
        end
        self.where(id: my_tweet_id_array)
    end
    
    
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: %i[ show edit update destroy retweet]
  skip_before_action :verify_authenticity_token



  # GET /tweets or /tweets.json
  def index
    @users = User.all.order("created_at DESC").page(params[:page]).per(10).where.not(id: current_user&.id)
    @tweet = Tweet.new
    @q = Tweet.ransack(params[:q]) #los resultados serán procesados por ransack
    
    if signed_in?
      @tweets = Tweet.tweets_for_me(current_user).order("created_at DESC").page(params[:page])
    else
      @tweets = Tweet.all.order("created_at DESC").page(params[:page])
    end

    if params[:tweetsearch].present?
      @tweets = Tweet.search_my_tweets(params[:tweetsearch]).page(params[:page]).order("created_at DESC")
    elsif params[:hashtag].present?
      @tweets = Tweet.search_my_tweets("##{params[:hashtag]}").page(params[:page]).order("created_at DESC")
    
      
    end
    #render json: @tweets
  end

  # GET /tweets/1 or /tweets/1.json
  def show
  
  end
  
  # GET /tweets/new
  def new
    if user_signed_in?
    @tweet = Tweet.new
    else
    redirect_to new_user_session_path
    end
    
  end
    #@tweet = current_user.tweets.build


  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets or /tweets.json
  def create
    
      #@tweet = Tweet.new(content: params(user: current_user))
      @tweet = current_user.tweets.build(tweet_params)

      respond_to do |format|
        if @tweet.save
          format.html { redirect_to root_path, notice: "Tweet was successfully created." }
          #format.json {render json: @tweet, status: :created}
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @tweet.errors, status: :unprocessable_entity }
        end
      end 
    #end
  end

  # PATCH/PUT /tweets/1 or /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: "Tweet was successfully updated." }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1 or /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: "Tweet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def retweet
    redirect_to root_path, alert: 'No es posible hacer retweet' and return if @tweet.user == current_user
    retweeted = Tweet.new(content: @tweet.content)
    retweeted.user = current_user
    retweeted.rt_ref = @tweet.id
    if retweeted.save
        @tweet.update(retweet: @tweet.retweet = 1)
      
        redirect_to root_path, notice: 'Retweet was posted successfully.'
    else
        redirect_to root_path, alert: "Unable to retweet."
    end
  end

  def follower 
    @tweet = Tweet.find(params[:tweet_id])
    @friend = Friend.create(user_id: current_user.id, friend_id: params[:user_id])
    Friend.create(user_id: current_user.id, friend_id: @tweet.user_id)
    redirect_to root_path, notice: "Ahora sigues a #{@tweet.user.user_name}"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:content, :user_id, :retweet)
    end
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/_form.html.erb
<!--<div class="text center mx-auto col-md-3 offset-md-2">
  <%#= search_form_for @q do |f| %> 
  <div class="text center form-group">
      <%#= f.label :content_cont, "Search" %>
      <%#= f.search_field :content_cont, class: "form-control", placeholder: "Search" %>
      <%#= f.submit "Search", class: "btn btn-primary" %> 
  <%# end %>
  </div>
</div>-->

<br>

<br>
<%= form_with(model: tweet, local: true) do |form| %>
  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="card text-center mx-auto col-md-6 mb-3">
    <h3 class="card-title py-3">¿Qué está pasando?</h3>
    <div class="form-group">
        <%= form.text_area(:content, rows: 3, class: 'col-md-7') %>
    </div>
    <div class="actions my-2">
      <%= form.submit "Twittea", :class => 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<!--Modificar la página principal para que, si el usuario ha iniciado sesión, se muestren únicamente los tweets de las personas que sigue-->

<!-- Verificamos que el usuario este logeado para poder crear tweets y seguir amigos -->
<% if  user_signed_in?%>
    <%= render 'form', tweet: @tweet %>
<%end %>  

    <%= render "shared/friends" %>



<% @tweets.each do |tweet| %>

    <div class="card col-md-6 mb-3 bg-light tweet-list">
        <div class="row no-gutters">
            <div class="col-md-2 py-4"> 
                <img src="<%= tweet.user&.user_photo %>"width="80" height="80" class="rounded-circle mb-2 mx-4" >  
            </div>
            <div class="col-md-8">
                <div class="card-body">
                    <h5 class="card-user pr-8"><%= tweet.user.user_name %> .
                        <small class="text-muted display-12"><%= link_to time_ago_in_words(tweet.created_at),tweet %></small>
                    </h5>
                    <p class="card-text">
                    <% content_tweet_array = tweet.content.split%>
                    <% content_tweet_array.each do |element|%>
                        <% if element.start_with?("#") %>
                            <% element.slice!(0) %>
                            <a href="?hashtag=<%= element %>">#<%= element %></a>
                        <% else %>
                        <%= element %>
                        <% end %>
                    <% end %>  
                    </p>  
                </div>
            </div>
            <% if user_signed_in? %>
                <div class="col-md-2">
                <small class="text-muted"><%= link_to 'Show', tweet %></small>
                <% if tweet.user_id == current_user.id %>
                    <small class="text-muted"><%= link_to 'Edit', edit_tweet_path(tweet) %></small>
                    <small class="text-muted"><%= link_to 'Delete', tweet, method: :delete, data: { confirm: 'Are you sure?' }  %></small>
                <%end%>
                </div>
            <%end%>
        </div>

        <div class="row">
            <div class="col-md-4">
                <% if !tweet.rt_ref.nil? %>
                    <small class="text-muted ms-4"><%= link_to "#{tweet.user.user_name} lo retwitteó", tweet.retweet_ref %></small>
                <% end %>
            </div>

            <div class="col-md-4">
                <%= link_to retweet_tweet_path(tweet), data: { confirm: 'do you want to retweet'}, method: :post do %>
                    <span class="icon"><i class="fas fa-retweet fa"></i></span>
                <% end %>
                <%= tweet.retweet %>     
            </div>


                <%= tweet.likes.count %>
                <% if user_signed_in? %>
                    <div class="col-md-2">
                        <% if like(tweet, current_user) %>
                            <%= link_to tweet_like_path(tweet,like(tweet, current_user)), method: :delete do %>
                                <span class="icon-danger"><i class="fas fa-heart fa"></i></span>
                            <%end%>  
                    </div>

                        <% else  %>
                    <div class="col-md-2">
                            <%= link_to tweet_likes_path(tweet), method: :post do %>
                                <span class="icon-white"><i class="far fa-heart fa"></i></span>
                            <%end%>
                    </div>  
                        <%end%>
                <%end%>
        </div>
    </div>
</div>
<% end %>


<div class="text-center"><%= link_to_next_page @tweets, '>>Show More Tweets' %> |
    <%= link_to_prev_page @tweets, '<<Show Previous Tweets' %>
</div>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<div class="container">
<p  id="notice"><%= notice %></p>

<p>
<strong>Photo:</strong>
<img src="<%= @tweet.user.user_photo %>" width="60" height="60" class="rounded-circle mb-2">
</p>

<p>
<strong>Name:</strong>
<%= @tweet.user.user_name %>
</p>

<p>
<strong>Content:</strong>
<%= @tweet.content %>
</p>




<div class="container">
  <h2>Likes</h2>

  <div class="container">
    <!-- iteramos los likes para traer los id de usuario y luego sus fotos -->
    <p><%= @tweet.likes.count %> <%= (@tweet.likes.count) == 1 ? 'Like' : 'Likes'%></p>
    <div>
      <% Like.where(tweet_id: @tweet.id).each do |photo| %>
        <% user_photo =  photo.user_id %>
          <div class="d-inline-block p-2">
            <img src="<%= User.find(user_photo).user_photo%>" width="60" height="60" class="rounded-circle">
            <p><%= User.find(user_photo).user_name %></p>
          </div>
      <% end %>
    </div>
  </div>

  <br>
  
  <%= link_to 'Back', tweets_path %>
</div>