config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :tweets do 
    #post :follower #es el metodo creado en tweet controller para poder crear el seguir friend
    resources :likes 
    member do
      post :retweet #es el metodo creado en tweet controller para dar la acción 
    end
  end

  namespace :api do
    resources :tweets
  end

  # resources :users do 
  #   resources :friends
  # end

  get '/:hashtag', to: 'tweets#hashtag_search', as: 'hashtag'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
    } 

    devise_scope :user do
      post 'follow/:id', to: 'friends#follow', as: 'follow_user'
    delete 'follow/:id', to: 'friends#unfollow', as: 'unfollow_user'
    end
    
    get '/api/news', to: 'api/apis#index'
    get "/api/:date1/:date2", to: 'api/apis#date'
    post '/api/create', to: 'api/apis#create'
    get 'mytweets/index'

  root "tweets#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_friends.html.erb
<aside class="users-list">
  <% if  user_signed_in?%> 
      <h3 class="text-center">A quién seguir</h3>
      <br>
    
    <!--usuarios-->

    <% @users.each do |user|%>
      <% if pre_follow(user)%>
          <div class="text-center">
                <img src="<%= user.user_photo %>"width="60" height="60" class="rounded-circle mb-2 mx-4" >
                <h5 class="user_name pl-2"><%= user.user_name %></h5>
                <%= button_to "unfollow", unfollow_user_path(user.id), method: :delete, :class => 'btn btn-outline-light mx-4'%>
                <br>
            <div>
        <% else %>
          <div class="text-center">
                <img src="<%= user.user_photo %>"width="60" height="60" class="rounded-circle mb-2 mx-4" >
                <h5 class="user_name pl-2"><%= user.user_name %></h5>
                <%= button_to "follow", follow_user_path(user.id), method: :post, :class => 'btn btn-outline-light mx-4'%>
                <br>
            <div>
      <% end %>
    <% end %> 
  <%end%>

</aside>
  

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-info">
    <div class="my-auto mx-4">
        <a class="navbar-brand text-white" href="<%=root_path %>"><strong> Inicio</strong><i class="fab fa-twitter"></i></a>
    </div>
    <ul class="navbar-nav">
        <% if user_signed_in? %>
            <li><%= button_to "Logout", destroy_user_session_path, method: :delete, :class => 'btn btn-primary mx-4'  %></li>
            <li><%= button_to "My Tweets", mytweets_index_path, method: :get, :class => 'btn btn-primary mx-4'  %></li>
        <% else %>
            <li><%= button_to 'Ingresar', new_user_session_path, :class => 'btn btn-primary mx-4' %></li>
            <li><%= button_to 'Registrarse', new_user_registration_path, method: :get, :class => 'btn btn-primary mx-4' %></li>
        <% end %>
    </ul>

    <% if user_signed_in?  %>
        <div class="container mx-auto">
            <b><p class="text-white" >Bienvenido(a) <%= current_user.user_name %> <img src="<%= current_user.user_photo %>" width="40" height="40" class="rounded-circle mb-2" ></p></b>
        </div>
    <%end%>
    <br>

    <form class="form-inline">
        <div class="d-inline-block">
            <input class="form-control" type="search" placeholder="Buscar" aria-label="Buscar" name="tweetsearch">
        </div>
        <div class="d-inline-block">
            <button class="btn btn-outline-light" type="submit">Buscar</button>
        </div>
    </form>

</nav>